### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai201-stepanenko#10]
https://drive.google.com/file/d/1JyDN82JcLyx0T7sfTc0DpPWHgLITt2Rg/view?usp=sharing

**Comment by Sogetx** [comment]
1. Завдання
Інформаційна потреба у доступності їжі забезпечена мапою з розшташуванням найближчих магазин та супермаркетів.
Інформаційна потреба у зрозумілості їжи забезпечена необхідністю купувати їжу дешевше.
Інформаційна потреба у актуальності їжи забезпечена постійним оновленням цін продуктів.
2. Завадання
"Авторизація користувача" забезпечує можливість увійти до додатку та користуватися його функціями(перегляд курсів, їх створення та інше) що наближає нас до фінансової стабільності.
"Створення курсів" забезпечує можливість створити курс та отримувати за це гроші що наближає нас до фінансової стабільності.
"Замовлення їжі" забезпечує можливість шукати та замовляти їжу дешевшу за середню ринкову ціну що наближає нас до фінансової стабільності.

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
